### GET /tasks
http://localhost:5000/tasks

### GET /tasks/:id
http://localhost:5000/tasks/123

### POST /tasks
POST http://localhost:5000/tasks
Content-Type: application/json

{
  "title":"Design e-bud backend",
  "description":"Design and start building the e-bud project's frontend and backend",
  "priority":"high",
  "userId": 6
}

### PUT /tasks/:id
PUT http://localhost:5000/tasks/1
Content-Type: application/json

{
  "priority": "medium",
  "status": ""
}

### DELETE /tasks/:id
DELETE http://localhost:5000/tasks/1
### POST /auth/register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "test_user",
  "password": "test@123"
}

### POST /auth/login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "test_user",
  "password": "test@123"
}

### GET /profile (protected)
GET http://localhost:5000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTc5MDc1OTE5NSwiZXhwIjoxNzkzMzUxMTk1fQ.tt9T9CZMQObBDwXDbEdB6_sHPoON-19Rh-3myNmIeos